import streamlit as st 
from diffusers import StableDiffusionPipeline
import torch

def generate_images_using_huggingface_diffusers(text):
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
    pipe = pipe.to("cuda")
    prompt = text
    image = pipe(prompt).images[0] 
    return image

st.subheader("Image generation using Huggingface Diffusers")
input_prompt = st.text_input("Enter your text prompt")
if input_prompt is not None:
  if st.button("Generate Image"):
      image_output = generate_images_using_huggingface_diffusers(input_prompt)
      st.info("Generating image.....")
      st.success("Image Generated Successfully")
      st.image(image_output, caption="Generated by Huggingface Diffusers")